/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_edd;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.xml.sax.SAXException;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;


public class Inicio extends javax.swing.JFrame {
ListaNodo primero;
  int contador;
  ListaNodo ultima;
  
   
    public Inicio() {
        initComponents();
    }
 private String nombre;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("StateOfDreaming", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 51, 0));
        jButton2.setText("Ingresar Usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("StateOfDreaming", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("Leer Archivo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton4)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    public void leerarchivo(){
         
     
        
    }
    //cambiarla cuando lea archivo
    public void IngresarPalabra(ListaNodo palabras){
        
              
       if(primero == null){
           primero = ultima=palabras;
           //ultima=palabras;
             System.out.println("Palabra en Listad:" +palabras.palabra);
       }else{
           ultima.siguiente = palabras;
           ultima=palabras;
           ultima.siguiente=null;
       
       
           System.out.println("Palabra en Lista:" +palabras.palabra);
          
       }
        
       
       
       
    
       
       
    }
    
public void EscribirArchi(){
    String texArchivo = "digraph ListaPalabras"+contador +"{\n";
    ListaNodo bandera = new ListaNodo();
    bandera = primero;
    do{
         if(bandera== primero && bandera == ultima){
           texArchivo = texArchivo+bandera.palabra+";";
            
       }
         else if (bandera == primero){
             texArchivo = texArchivo + bandera.palabra;
        }
         else if(bandera == ultima){
             texArchivo=texArchivo+"->"+bandera.palabra+";";
         }
         else{
             texArchivo=texArchivo+"->"+bandera.palabra+";"+bandera.palabra;
         }
            
       bandera = bandera.siguiente;
    }while(bandera != null);
     texArchivo = texArchivo + "}";
    // jTextArea1.setText(texArchivo);
     
     try{
         File archi = new File("C:\\release\\EDD\\Palabras.txt");
         FileWriter fw = new FileWriter(archi,true);
         fw.write(texArchivo);
         fw.close();
         
     }catch(IOException ex){
    }
     
    }
        
        
        
    
     
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario();
        Tablero tablero = new Tablero();
        usuario.setVisible(true);
            EscribirArchi();
            tablero.CrearImg2();
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("XML FILES", "xml");
        fileChooser.setFileFilter(filter);
        fileChooser.showOpenDialog(null);

        File texto = fileChooser.getSelectedFile();

        try {
            DocumentBuilderFactory factoria = DocumentBuilderFactory.newInstance();
            DocumentBuilder Builder = factoria.newDocumentBuilder();
            Document doc = Builder.parse(texto);
            doc.getDocumentElement().normalize();
 //-------------------------------------------------------          
          NodeList lisDimension = doc.getElementsByTagName("dimension");
          for(int i=0;i<lisDimension.getLength();i++){  
          Node nodo = lisDimension.item(i);
             Element dimen =(Element)nodo;
            // NodeList ldimen = dimen.getElementsByTagName("dimension");   
          System.out.println("Dimen"+dimen.getTextContent());
          }
            
            
//-----------------------------------------------------------            
            NodeList lisDi = doc.getElementsByTagName("diccionario");
            Node node = lisDi.item(0);
            Element palabras = (Element) node;
            NodeList lPalabra = palabras.getElementsByTagName("palabra");

            for (int i = 0; i < lPalabra.getLength(); i++) {
                Node palabra = lPalabra.item(i);
                Element elemento = (Element) palabra;
                ListaNodo varpal = new ListaNodo(elemento.getTextContent());
           IngresarPalabra(varpal);
           
                System.out.println("Palabra: " + elemento.getTextContent());
            }
            //-------------------------------------------------
            
            
             
            
            
            
            
            
        } catch (ParserConfigurationException | SAXException | IOException e) {
            System.out.println("Error");
        }
            
            
            
            
      
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
