package practica1_edd;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Astrid Hernandez
 */
public class Tablero extends javax.swing.JFrame {

    int contador;
    Cola Letraentrega = null;
    Cola inicioLetra = null;
    Cola ultimaLetra = null;
    Cola colasale = new Cola();
    int cA=12;
    int ca=0;
    int cB=2;
    int cb=0;
    int cC=4;
    int cc=0;
    int cD=5;
     int cd=0;
    int cE=12;
     int ce=0;
    int cF=1;
     int cf=0;
    int cG=2;
     int cg=0;
    int cH=2;
     int ch=0;
    int cI=6;
     int ci=0;
    int cJ=1;
     int cj=0;
   
    int cL=4;
     int cl=0;
    int cM=2;
     int cm=0;
    int cN=5;
     int cn=0;
      int cÑ=1;
     int cñ=0;
    int cO=9;
     int co=0;
    int cP=2;
     int cp=0;
    int cQ=1;
     int cq=0;
    int cR=5;
     int cr=0;
    int cS=6;
     int cs=0;
    int cT=4;
     int ct=0;
    int cU=5;
     int cu=0;
    int cV=1;
     int cv=0;
  
    int cX=1;
     int cx=0;
   int cY=1;
   int cy = 0;
    int cZ=1;
     int cz=0;
    
    
    
    public Tablero() {
        
        initComponents();
     //  CrearImg();
    //   CrearImg2();
      
 agrCola();
 //turno();

    }
public void CrearImg(){
   
    try {
    
      
      String dotPath = "C:\\release\\bin\\dot.exe";
      
      String fileInputPath = "C:\\release\\EDD\\Jugadores.txt";
      String fileOutputPath = "C:\\Users\\Astrid Hernandez\\Documents\\GitHub\\Practica1s12017_201213223\\Practica1_EDD\\src\\practica1_edd\\Imagenes\\Jugadores.png";
      
      String tParam = "-Tjpg";
      String tOParam = "-o";
        
      String[] cmd = new String[5];
      cmd[0] = dotPath;
      cmd[1] = tParam;
      cmd[2] = fileInputPath;
      cmd[3] = tOParam;
      cmd[4] = fileOutputPath;
                  
      Runtime rt = Runtime.getRuntime();
      
      rt.exec( cmd );
      
    } catch (Exception ex) {
      ex.printStackTrace();
    } finally {
    }

}

public void CrearImg2(){
    try {
      
      String dotPath = "C:\\release\\bin\\dot.exe";
      
      String fileInputPath = "C:\\release\\EDD\\Palabras.txt";
      String fileOutputPath = "C:\\Users\\Astrid Hernandez\\Documents\\GitHub\\Practica1s12017_201213223\\Practica1_EDD\\src\\practica1_edd\\Imagenes\\Palabras.png";
      
      String tParam = "-Tjpg";
      String tOParam = "-o";
        
      String[] cmd = new String[5];
      cmd[0] = dotPath;
      cmd[1] = tParam;
      cmd[2] = fileInputPath;
      cmd[3] = tOParam;
      cmd[4] = fileOutputPath;
                  
      Runtime rt = Runtime.getRuntime();
      
      rt.exec( cmd );
      
    } catch (Exception ex) {
      ex.printStackTrace();
    } finally {
        
    }
}
public void crear(int dimension){
    
    for (int j = 0; j < dimension; j++) {
            for (int i = 0; i < dimension; i++) {

        

            }
        }
}

/*public void turno(){
    jTextField1.setText("");
    Usuario usu = new Usuario();
   jLabel3.setText(usu.primero.nombre);
    UsuarioNodo turno = new UsuarioNodo();
    while(turno != null){
        if(turno == usu.ultimo){
           jTextField1.setText(jTextField1.getText()+turno.nombre);
            break;
        }else{
           turno = turno.siguiente; 
        }
    }
}*/
    /**(
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jButton8 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton8.setText("Asignar Letra");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Astrid Hernandez\\Documents\\GitHub\\Practica1s12017_201213223\\Practica1_EDD\\src\\practica1_edd\\Imagenes\\Palabras.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jScrollPane1.setViewportView(jLabel1);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Astrid Hernandez\\Documents\\GitHub\\Practica1s12017_201213223\\Practica1_EDD\\src\\practica1_edd\\Imagenes\\Jugadores.png")); // NOI18N
        jScrollPane2.setViewportView(jLabel2);

        jTabbedPane1.addTab("tab2", jScrollPane2);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Astrid Hernandez\\Documents\\GitHub\\Practica1s12017_201213223\\Practica1_EDD\\src\\practica1_edd\\Imagenes\\Cola.png")); // NOI18N
        jLabel10.setText("jLabel10");
        jScrollPane3.setViewportView(jLabel10);

        jTabbedPane1.addTab("tab3", jScrollPane3);

        jButton1.setText("Crear Imagen");
        jButton1.setActionCommand("CrearCola");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
        
       sacarCola();
      
        
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DiagramaArchivo();
        CrearImgCola();
        this.setVisible(true);
        
       
       
                
    }//GEN-LAST:event_jButton1ActionPerformed

     public void agregarLetra(Cola Letraactual, int ingreso){
        if(inicioLetra == null){
            inicioLetra = Letraactual;
            ultimaLetra = Letraactual;
            
        }else{
            ultimaLetra.siguiente = Letraactual;
            ultimaLetra = Letraactual;
        }
            
        }
    
    
    public void RandomCola(int valor){
        //hacer el random para llenar cola
        int random=(int)(Math.random()*25)+1;
        switch(random){
            case 1:
                if(ca<cA){
                   Cola la = new Cola("A",1);
                 agregarLetra(la,valor);
                 ca++;
                 
                }
            break;
            case 2:
            if(cb<cB){
                   Cola lb = new Cola("B",3);
                 agregarLetra(lb,valor);
                 cb++;
                 
                } 
            break;
            case 3:
            if(cc<cC){
                   Cola lc = new Cola("C",3);
                 agregarLetra(lc,valor);
                 cc++;
                 
                }
            break;
            case 4:
                if(cd<cD){
                   Cola ld = new Cola("D",2);
                 agregarLetra(ld,valor);
                 cd++;
                 
                }
                break;
            case 5:
            if(ce<cE){
                   Cola le = new Cola("E",1);
                 agregarLetra(le,valor);
                 ce++;
                 
                }
            break;
            case 6:
                if(cf<cF){
                   Cola lf = new Cola("F",4);
                 agregarLetra(lf,valor);
                 cf++;
                 
                }
            break;
            case 7:
                if(cg<cG){
                   Cola lg = new Cola("G",2);
                 agregarLetra(lg,valor);
                 cg++;
                 
                }
            break;
            case 8:
                if(ch<cH){
                   Cola lh = new Cola("H",4);
                 agregarLetra(lh,valor);
                 ch++;
                 
                }
            break;
            case 9:
                if(ci<cI){
                   Cola li = new Cola("I",1);
                 agregarLetra(li,valor);
                 ci++;
                 
                }
            break;
            case 10:
                if(cj<cJ){
                   Cola lj = new Cola("J",8);
                 agregarLetra(lj,valor);
                 cj++;
                 
                }
            break;
            case 11:
                if(cl<cL){
                   Cola ll = new Cola("L",1);
                 agregarLetra(ll,valor);
                 cl++;
                 
                }
            break;
            case 12:
                if(cm<cM){
                   Cola lm = new Cola("M",3);
                 agregarLetra(lm,valor);
                 cm++;
                 
                }
            break;
            case 13:
                if(cn<cN){
                   Cola ln = new Cola("N",1);
                 agregarLetra(ln,valor);
                 cn++;
                 
                }
            break;
                    case 14:
                        if(cñ<cÑ){
                   Cola lñ = new Cola("Ñ",8);
                 agregarLetra(lñ,valor);
                 cñ++;
                 
                }
                    break;
                    case 15:
                        if(co<cO){
                   Cola lo = new Cola("O",1);
                 agregarLetra(lo,valor);
                 co++;
                 
                }
                   break;
                    case 16:
                        if(cp<cP){
                   Cola lp = new Cola("P",3);
                 agregarLetra(lp,valor);
                 cp++;
                 
                }
                    break;
                    case 17:
                        if(cq<cQ){
                   Cola lq = new Cola("Q",5);
                 agregarLetra(lq,valor);
                 cq++;
                 
                }
                    break;
                    case 18:
                        if(cr<cR){
                   Cola lr = new Cola("R",1);
                 agregarLetra(lr,valor);
                 cr++;
                 
                }
                    break;
                    case 19:
                        if(cs<cS){
                   Cola ls = new Cola("S",1);
                 agregarLetra(ls,valor);
                 cs++;
                 
                }
                    break;
                    case 20:
                        if(ct<cT){
                   Cola lt = new Cola("T",1);
                 agregarLetra(lt,valor);
                 ct++;
                 
                }
                    break;
                    case 21:
                        if(cu<cU){
                   Cola lu = new Cola("U",1);
                 agregarLetra(lu,valor);
                 cu++;
                 
                }
                    break;
                    case 22:
                        if(cv<cV){
                   Cola lv = new Cola("V",4);
                 agregarLetra(lv,valor);
                 cv++;
                 
                }
                    break;
                    case 23:
                        if(cx<cX){
                   Cola lx = new Cola("X",8);
                 agregarLetra(lx,valor);
                 cx++;
                 
                }
                    break;
                    case 24:
                        if(cy<cY){
                   Cola ly = new Cola("Y",4);
                 agregarLetra(ly,valor);
                 cy++;
                 
                }
                    break;
                    case 25:
                        if(cz<cZ){
                   Cola lz = new Cola("Z",10);
                 agregarLetra(lz,valor);
                 cz++;
                 
                }
                    break;
                    default:
                        break;
        }
        }
    
    
public void agrCola(){
    for(int valor = 1; valor<96;valor++){
       RandomCola(valor);
     
    }
}
public void recorrerCola(){
    int conta = 1;
    Cola aux = new Cola();
    aux=inicioLetra;
    do{
        
    aux=aux.siguiente;
    conta++;
        
    } while(aux != ultimaLetra.siguiente);
    System.out.println("tantas letras"+conta);
 

}

public void sacarCola(){
   
    colasale = inicioLetra;
    Cola nuevo = new Cola();
    nuevo = inicioLetra.siguiente;
    inicioLetra=nuevo;
    recorrerCola();
    
        recorrerCola();
    System.out.println("sale"+nuevo.letra);
      //jLabel4.setText(nuevo.letra);
    
}
 public void DiagramaArchivo(){
    String texArchivo = "digraph ListaCola"+contador +"{\n";
    Cola bandera = new Cola();
    bandera = inicioLetra;
    do{
         if(bandera== inicioLetra && bandera==ultimaLetra){
           texArchivo = texArchivo+bandera.letra+";";
       
        }
         else if(bandera == inicioLetra){
             texArchivo = texArchivo + bandera.letra;
             
        } else if(bandera== ultimaLetra){
            texArchivo = texArchivo +"->"+ bandera.letra+"->"+inicioLetra.letra+";\n";
            
       }
    else{
             texArchivo = texArchivo +"->"+ bandera.letra+";\n"+bandera.letra;
        }
            
       bandera = bandera.siguiente;
    }while(bandera != null);
     texArchivo = texArchivo + "}";
    // jTextArea1.setText(texArchivo);
     
     try{
         File archi = new File("C:\\release\\EDD\\Cola.txt");
         FileWriter fw = new FileWriter(archi,true);
         fw.write(texArchivo);
         fw.close();
         
     }catch(IOException ex){
    }
 }
 
 public void CrearImgCola(){
   
    try {
    
      
      String dotPath = "C:\\release\\bin\\dot.exe";
      
      String fileInputPath = "C:\\release\\EDD\\Cola.txt";
      String fileOutputPath = "C:\\Users\\Astrid Hernandez\\Documents\\GitHub\\Practica1s12017_201213223\\Practica1_EDD\\src\\practica1_edd\\Imagenes\\Cola.png";
      
      String tParam = "-Tjpg";
      String tOParam = "-o";
        
      String[] cmd = new String[5];
      cmd[0] = dotPath;
      cmd[1] = tParam;
      cmd[2] = fileInputPath;
      cmd[3] = tOParam;
      cmd[4] = fileOutputPath;
                  
      Runtime rt = Runtime.getRuntime();
      
      rt.exec( cmd );
      
    } catch (Exception ex) {
      ex.printStackTrace();
    } finally {
    }

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
